### ISSUE TITLE
Npm install error, permission denied 

### ISSUE THREAD

**Issue by chornos13** [huan/node-facenet#157]
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
Jakarta
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
Localhost
### Expected behavior

`npm install facenet`

successfuly installed

### Actual behavior

install error

### Steps to reproduce the behavior (and fixes, if any)
`npm install facenet`

### Full Output Logs
```shell
# PASTE RELATED FULL LOG OUTPUT AT HERE:
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/zixia/blessed-contrib.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

```

**Comment by huan** [comment]
This is because my code dependence a repo from my GitHub account before, but I delete that repository so it can not be found anymore.

I will try to figure out how to fix it when I have time, or you can try to replace `ssh://git@github.com/zixia/blessed-contrib.git` to <https://www.npmjs.com/package/blessed-contrib>

**Comment by chornos13** [comment]
> This is because my code dependence a repo from my GitHub account before, but I delete that repository so it can not be found anymore.
> 
> I will try to figure out how to fix it when I have time, or you can try to replace `ssh://git@github.com/zixia/blessed-contrib.git` to https://www.npmjs.com/package/blessed-contrib

How can i replace that ?

**Comment by best-tech** [comment]
i need help too

**Comment by adhityan** [comment]
I see this is fixed in master but not yet published to npm. There have been no updates pushed to npm since the past two years?!

I got around this problem by installing directly from the repo -

`yarn add https://github.com/huan/node-facenet.git`

**Comment by huan** [comment]
Hi @adhityan , thanks for letting me know the DevOps pipeline is not working in the past 2 years.

I'll take a look at it later.

**Comment by gabdez** [comment]
@huan Could you please tell me how to install your package via npm? I tried @adhityan solution but its not working
thanks

**Comment by WirothKaewtue** [comment]
Now still can't install.  
`
npm ERR! code 128
npm ERR! command failed
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/zixia/blessed-contrib.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/developer/.npm/_logs/2022-03-01T10_45_11_295Z-debug.log`

**Comment by huan** [comment]
This project has not been maintained for a long time, it is very hard to be set up for now.

Please consider to use [face-api.js](https://itnext.io/face-api-js-javascript-api-for-face-recognition-in-the-browser-with-tensorflow-js-bcc2a6c4cf07)
